"""empty message

Revision ID: 04ae6259456a
Revises: 7b11e8ca5f6f
Create Date: 2019-11-06 16:10:11.094898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04ae6259456a'
down_revision = '7b11e8ca5f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_pg2', sa.Column('AC_x', sa.Float(), nullable=True))
    op.add_column('books_pg2', sa.Column('AC_y', sa.Float(), nullable=True))
    op.add_column('books_pg2', sa.Column('AC_z', sa.Float(), nullable=True))
    op.drop_column('books_pg2', 'num_pages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_pg2', sa.Column('num_pages', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('books_pg2', 'AC_z')
    op.drop_column('books_pg2', 'AC_y')
    op.drop_column('books_pg2', 'AC_x')
    # ### end Alembic commands ###
