"""empty message

Revision ID: 54adfa960146
Revises: 04ae6259456a
Create Date: 2019-11-06 16:19:24.703299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54adfa960146'
down_revision = '04ae6259456a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_pg2', sa.Column('PC_x', sa.Float(), nullable=True))
    op.add_column('books_pg2', sa.Column('PC_y', sa.Float(), nullable=True))
    op.add_column('books_pg2', sa.Column('PC_z', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_pg2', 'PC_z')
    op.drop_column('books_pg2', 'PC_y')
    op.drop_column('books_pg2', 'PC_x')
    # ### end Alembic commands ###
