"""empty message

Revision ID: 7b11e8ca5f6f
Revises: 
Create Date: 2019-11-06 15:53:45.144828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b11e8ca5f6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_pg2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_pages', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_pg2')
    # ### end Alembic commands ###
